=== ducnguyenedures/prx301-xml/class2/book.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           version="1.0">
    <xs:element name="Books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"></xs:minLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Author" type="xs:string"></xs:element>
                            <xs:element name="Price" type="xs:float"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="Category" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ducnguyenedures/prx301-xml/class2/book_gen.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="book.xsd">
    <Book Category="">
        <Name>aaaaa</Name>
        <Author>a</Author>
        <Price>10.0</Price>
    </Book>
    <Book Category="">
        <Name>abcde</Name>
        <Author>a</Author>
        <Price>10.0</Price>
    </Book>
    <Book Category="">
        <Name>a12345</Name>
        <Author>a</Author>
        <Price>10.0</Price>
    </Book>
</Books>
